CenterForOpenScience/ember-share

app/adapters/application.js
app/adapters/elastic-search-result.js
app/components/search-facet-typeahead/component.js
app/components/search-facet-typeahead/template.hbs
app/utils/build-query-string.js

May need to add `@method_decorator(csrf_exempt)` decorator in the api.

add typeahead to search page and fix some syntax

---

app/components/search-result/template.hbs

Wait for elastic search to return person ids

[hold] add link to person page for contributors

---

app/components/search-result/component.js
app/components/search-result/template.hbs
app/templates/discover.hbs

* also add container on discover page

limit contributors and tags shown on discover page

---

app/components/search-result/template.hbs
app/controllers/discover.js
app/templates/discover.hbs

Resolves #17 
* created `addFilter` action

[Feature] Add filter when tag is clicked

---

app/controllers/discover.js
app/templates/discover.hbs

Fix #37 and clean up some code.

'More' button that isn't lying.

---

app/components/search-facet-language/component.js
app/controllers/discover.js
app/controllers/sources.js

Resolves #38 
* Prevent multiple of the same filter
* Fix language select
* Update sources search so that it uses the suggest endpoint

[Feature fix] language filter, tag filter, sources search

---

app/controllers/discover.js
app/styles/app.scss
app/templates/discover.hbs

Add atom feed button

---

app/routes/discover.js

* reset query params on exit
* reset facet filters on exit

Fix unusual query params behavior on page transitions

---

app/controllers/discover.js
app/templates/discover.hbs

Resolves #22 
* rearranged the search bar to display count information

Display search result count below search bar

---

app/components/search-result/style.css
app/components/search-result/template.hbs
app/controllers/discover.js
app/templates/discover.hbs

Note: this can still be improved and clicking on things other than tags will be fixed in another PR
* Display more in search results

[Feature] Display more information in search results

---

app/controllers/discover.js

Only query aggregations on first page of results

---

app/controllers/discover.js
app/templates/discover.hbs

Related ticket: #15 
* styling/placement to be done by @karleywalker

[Feature] add sort option

---

app/components/faceted-search/component.js
app/components/faceted-search/template.hbs
app/components/search-facet-association/component.js
app/components/search-facet-daterange/component.js
app/components/search-facet-language/component.js
app/components/search-facet-person/component.js
app/components/search-facet-source/component.js
app/components/search-facet-source/template.hbs
app/components/search-facet-typeahead/component.js
app/components/search-facet-worktype-button/component.js
app/components/search-facet-worktype/component.js
app/components/search-result/template.hbs
app/controllers/discover.js
app/controllers/sources.js
app/routes/discover.js
app/templates/discover.hbs
app/templates/sources.hbs
app/utils/elastic-query.js

* fixes all of the double selection and transition facet bugs
* selection of filters from the search results is not currently implemented and will be in another PR

[Feature] facet refactor

---

app/controllers/discover.js
app/templates/discover.hbs

Add basic no results message

---

app/components/navbar-component/template.hbs
app/components/provider-block/template.hbs
app/templates/discover.hbs
app/templates/sources.hbs

* Discover page
* hide extra text under search bar
* hide search facets
* show clear filter button at top
* Hide "SHARE" on nav bar
* Use one column on sources page instead of two

[Feature] Make UI responsive for small screens

---

app/components/search-facet-typeahead/component.js

[Feature] Debounce autocomplete queries

---

app/controllers/discover.js
app/styles/app.scss
app/templates/discover.hbs

Show active filters at top on a small screen

---

app/components/curate-field-list/template.hbs
app/components/curate-field-text/style.scss
app/components/curate-field-text/template.hbs
app/components/curate-list-tag/style.scss
app/components/curate-list-tag/template.hbs
app/components/curate-person/template.hbs
app/components/curate-work/template.hbs
app/components/navbar-component/template.hbs

* comments out login functionality
* comments out edit functionality on curation pages
* hides possible merges

Disable all curation/login

---

app/controllers/discover.js
app/utils/elastic-query.js

Escape commas in query params

---

app/components/faceted-search/style.scss
app/components/search-facet-worktype/style.scss
app/components/search-facet-worktype/template.hbs
app/components/search-result/style.css
app/components/search-result/template.hbs
app/styles/app.scss
app/templates/discover.hbs

- Styles facets in side bar
- Styles search results
- Styles search bar
- Styles 'Clear Filters' button

discover page styling

---

app/breakpoints.js
app/components/search-facet-language/component.js
app/components/search-facet-typeahead/component.js
app/components/search-facet-worktype/component.js
app/controllers/discover.js
app/templates/discover.hbs
package.json

Add option to show filters on small screen

---

app/controllers/index.js

Fix undefined search bug

---

app/templates/index.hbs

Add s to publication and preprint on homepage

---

app/templates/index.hbs

Update wording in footer

---

app/adapters/application.js
app/authenticators/osf-token.js
app/components/curate-field-list/component.js
app/components/curate-person/component.js
app/components/curate-work/component.js
app/components/footer-boxes/component.js
app/components/merge-widget/component.js
app/components/provider-block/component.js
app/components/search-facet-typeahead/component.js
app/controllers/discover.js
app/controllers/sources.js
app/utils/build-elastic-call.js
config/environment.js

Should be merged in conjunction with: https://github.com/CenterForOpenScience/SHARE/pull/421

Update urls to v2

---

app/components/curate-field-list/component.js
app/components/curate-field-list/template.hbs
app/components/curate-field-text/component.js
app/components/curate-field-text/template.hbs
app/components/curate-list-tag/component.js
app/components/curate-list-tag/template.hbs
app/components/curate-person/component.js
app/components/curate-person/template.hbs
app/components/curate-work/component.js
app/components/curate-work/template.hbs
app/components/navbar-component/component.js
app/components/navbar-component/template.hbs
config/environment.js
package.json

Unsure whether potential merges should be shown if curation is disabled or if user is logged out.

[Feature] Disable login based on environment variable

---

app/authenticators/osf-token.js

Resolves https://openscience.atlassian.net/browse/SHARE-413

Redirect login straight to OSF

---

app/components/progress-tracker/component.js
app/components/progress-tracker/style.css
app/components/progress-tracker/template.hbs
app/components/registration-status/template.hbs
app/controllers/registration/form.js
app/models/registration.js
app/routes/registration/form.js
app/styles/registration.css
app/templates/index.hbs
app/templates/profile.hbs
app/templates/registration/form.hbs

[Feature] registration form upgrade

---

app/models/registration.js
app/routes/registration/form.js
app/styles/registration.css
app/templates/registration/form.hbs

* Remove focus outline when errors
* Reset form on transition
* Clear form errors on valid submission

Registration QA bug fixes

---

app/components/curate-list-contributor/component.js
app/components/curate-list-contributor/template.hbs
app/components/curate-work/component.js
app/components/curate-work/template.hbs
app/components/navbar-component/component.js
app/components/navbar-component/template.hbs
app/components/suggest-login/component.js
app/controllers/registration/form.js
app/routes/registration/form.js
app/templates/registration/form.hbs

* Add GA for navbar
* Add GA for registration form
* Add GA for detail page

Add more analytics

---

app/components/curate-field-text/component.js
app/components/search-result/component.js
app/index.html

Apply mathjax to needed fields [SHARE-384]

---

app/mixins/detail.js
app/router.js
app/routes/curate.js
app/routes/detail.js
config/environment.js

* Redirect pks to new values
* Redirect curate to detail
* Fix entries error

[SHARE-446][2.0.0] Redirect old urls to new urls

---

app/components/search-result/style.css
app/components/section-tags/component.js
app/components/section-tags/style.css
app/components/section-tags/template.hbs

[Feature] Add space between tag rows

---

app/components/page-controls/component.js
app/components/page-controls/template.hbs
app/controllers/discover.js
app/templates/discover.hbs

* Limit pages to 1,000 and format numbers
* Move page navigation and Move sort select

[Feature] Fix 500 for large page navigation

---

app/controllers/discover.js
app/utils/elastic-query.js

[Feature] Update people filter

---

app/controllers/discover.js

Until we can move away from the suggester there isn't a great way to return accurate results.

[Feature] Remove organization and institution facet

---

app/adapters/application.js
app/serializers/application.js
app/serializers/registration.js

Haven't tested login because it's broken on local

[Feature] Update adapter and serializer

---

app/components/registration-status/template.hbs
app/controllers/registration/form.js
app/models/registration.js
app/serializers/registration.js

Update registration count check

[Feature] Update 'normalize response' for registration model

---

ember-cli-build.js

Fix the IE console error.
https://openscience.atlassian.net/browse/SHARE-469

[SHARE-469] [Feature] Include polyfill

---

app/controllers/discover.js

[SHARE-478][Feature] Use elastic source aggregations to set 'Aggregating sources' number

---

app/controllers/agent.js
app/controllers/discover.js
app/controllers/work.js
app/routes/discover.js
app/styles/app.scss
app/templates/agent.hbs
app/templates/work.hbs

Ticket: https://openscience.atlassian.net/browse/SHARE-477

[SHARE-477][Feature] Add back button on detail pages

---

app/components/cos-footer/component.js
app/components/cos-footer/style.scss
app/components/cos-footer/template.hbs
app/components/search-result/style.scss
app/components/search-result/template.hbs
app/components/suggest-login/template.hbs
app/styles/app.scss
app/templates/agent.hbs
app/templates/application.hbs
app/templates/discover.hbs
app/templates/index.hbs
app/templates/work.hbs

Add the copyright to all pages.
* Copyright on all pages
* New footer that has links
* something else can go there but it looks weird without a footer
* Cleaned up style in templates
* Removed "Developer docs" link from index page and added new version to footer
https://openscience.atlassian.net/browse/SHARE-468

[SHARE-468] [Feature] Add COS footer

---

app/components/search-result/component.js
app/components/search-result/template.hbs
app/controllers/work.js
app/templates/work.hbs

** related https://github.com/CenterForOpenScience/SHARE/pull/557
https://github.com/CenterForOpenScience/ember-share/pull/162 only rendered html in the description.
Render html in title.
None
https://openscience.atlassian.net/browse/SHARE-470

[SHARE-470][Feature] Render html in title

---

app/components/query-syntax/template.hbs
app/controllers/discover.js
app/templates/discover.hbs

Cleaner language in the error message for a malformed query.
Don't display the actual message from elasticsearch, which can be ugly and confusing. Instead, something nicer:
https://openscience.atlassian.net/browse/SHARE-480

[SHARE-480][Feature] Cleaner language on query error message

---

app/components/cos-footer/template.hbs
app/components/suggest-login/style.scss
app/components/suggest-login/template.hbs

Update the quick links in the footer so they work in all environments.
* Use `link-to` so links work locally and on staging/production
* Add some padding below the login suggest component
Before:
After:
None
https://openscience.atlassian.net/browse/SHARE-468

[SHARE-468][Feature] Use ember link-to in footer

---

app/adapters/application.js
app/adapters/registration.js
app/controllers/registration/form.js

*Related to https://github.com/CenterForOpenScience/SHARE/pull/560*
Update the source registration endpoint to resolve conflict with the creative work type `registration`.
Updated the registration adapter:
`registrations` --> `sourceregistrations`
None
https://openscience.atlassian.net/browse/SHARE-520

[SHARE-520][Feature] Update source registration endpoint

---

app/controllers/discover.js

Ingress --> Ingest
None
https://openscience.atlassian.net/browse/SHARE-571

[SHARE-571][Feature] Change ingress to ingest

---

app/components/provider-block/component.js
app/components/provider-block/style.css
app/components/provider-block/template.hbs

Use favicon url from API, added in CenterForOpenScience/SHARE#565
No 404 errors on `/sources`.
https://openscience.atlassian.net/browse/SHARE-511

[SHARE-511][Feature] Use favicon url from API, don't construct it

---

app/controllers/discover.js

Add a note about limiting pages since it's not obvious in the code.
Added a comment.
None
https://openscience.atlassian.net/browse/SHARE-596

[SHARE-596][Feature] Add note about limiting pages

---

app/components/sortby-dropdown/component.js
app/components/sortby-dropdown/styles.scss
app/components/sortby-dropdown/template.hbs
app/controllers/discover.js
app/templates/discover.hbs

Add label, 'Sort by', to sort selector to make the functionality more obvious to the user.
* Add 'Sort by' label
* Desc --> Newest first
* Asc --> Oldest first
*Code adopted from Preprints interface*
None
https://openscience.atlassian.net/browse/SHARE-602

[SHARE-602][Improvement] Add sort by label

---

app/controllers/index.js

Capitalize placeholder to match style of placeholders on the OSF.
None
https://openscience.atlassian.net/browse/SHARE-607

[SHARE-607][Improvement] Capitalize placeholder

---

app/components/section-sources/component.js
app/components/section-sources/style.css
app/components/section-sources/template.hbs

Set a consistent source icon size on detail pages.
Before:
After:
https://openscience.atlassian.net/browse/SHARE-651

[SHARE-651][Feature] Consistent source icon size on detail page.

---

app/utils/elastic-query.js

Filtering the discover page by date range doesn't include works from the "end" date.
The simplest way to see this is filtering to a single date, which previously returned no results:
Use [elasticsearch's date math](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-range-query.html#_date_math_and_rounding) to include the entire day within the search range.
Nope.
https://openscience.atlassian.net/browse/SHARE-639

[SHARE-639][Feature] Inclusive date range search.

---

app/components/provider-block/style.css
app/components/provider-block/template.hbs
app/components/section-sources/template.hbs
app/routes/detail.js

`source.favicon` became `source.icon` in CenterForOpenScience/SHARE#601, update the front end to match.
Expect `icon` from the API and rename things for consistency.
https://openscience.atlassian.net/browse/SHARE-630

[SHARE-630][Feature] Rename favicon => icon

---

app/components/cos-footer/style.scss
app/components/cos-footer/template.hbs
app/components/homepage-button-box/style.css
app/components/navbar-component/style.scss
app/components/search-result/template.hbs
app/styles/app.scss
app/templates/index.hbs
app/templates/sources.hbs

Limit all pages to the same width.
* limit all pages to same width
* use flex boxes in footer for better centering
* add redirect class to publisher link so it looks like the other links
None
https://openscience.atlassian.net/browse/SHARE-634

[SHARE-634][Improvement] Limit all page widths

---

app/components/cos-footer/style.scss
app/styles/app.scss
app/templates/profile.hbs

Limit profile page width.
* limit profile page width
* don't underline links in footer on hover
None
https://openscience.atlassian.net/browse/SHARE-634

[SHARE-634][Improvement] Limit profile width

---

app/components/page-controls/style.scss
app/components/search-result/style.scss
app/components/search-result/template.hbs

Add a filter when tag in clicked.
* make tags clickable
* remove underlines from pagination links
None
https://openscience.atlassian.net/browse/SHARE-634

[SHARE-634][Improvement] Clickable tags

---

.nvmrc
.travis.yml
app/controllers/discover.js
app/templates/discover.hbs
testem.js
yarn.lock

Change the wording in the search bar on the discover page to "Search scholarly works" so that it matches the language on the homepage.
* Change from events to works
* Add placeholder
https://openscience.atlassian.net/browse/SHARE-809

[SHARE-809][Feature]Consistent wording for search bar

---

app/components/cos-footer/template.hbs

Add link to status page
Replace link to share sources with COS status page 
https://openscience.atlassian.net/browse/SHARE-985

[Feature][SHARE-985] Add link to status

---

CHANGELOG.md

Backfill CHANGELOG.
* Added release notes for 2.10.0
* Added note about missing release numbers.
* Made the formatting consistent
https://openscience.atlassian.net/browse/SHARE-992

[SHARE-992][Fix] Backfill CHANGELOG.md

---

app/components/search-result/component.js
app/components/search-result/style.scss
app/components/search-result/template.hbs

Display the lineage added in https://github.com/CenterForOpenScience/SHARE/pull/723
Possibly ugly with long ancestor titles
https://openscience.atlassian.net/browse/SHARE-1000

[SHARE-1000][Feature] Display lineage in search results

---

app/adapters/registration.js

The adapter is needed for the profile page.
Added the registration adapter back.
None
https://openscience.atlassian.net/browse/SHARE-1009

[SHARE-1009][Fix] Add the registration adapter back

---

app/authenticators/osf-token.js

Fix login
https://openscience.atlassian.net/browse/SHARE-1037

[SHARE-1037][Fix] Fix the login

---

app/components/search-result/template.hbs
app/controllers/discover.js
app/controllers/index.js
app/templates/index.hbs

Fix bugs found during ember-share regression:
* type filter not working from landing page
* type filter not working from search results
* searchUrl not showing
* type --> types
* add back searchUrl
None
https://openscience.atlassian.net/browse/SHARE-1016

[SHARE-1016][Fix] Fix filters and search url

---

app/components/navbar-component/style.scss
app/components/navbar-component/template.hbs

Restore the navbar to it's normal height when logged in.
Make the padding when logged in higher priority.
None
https://openscience.atlassian.net/browse/SHARE-1037

[SHARE-1037][Fix] Update style for navbar

---

CHANGELOG.md
app/components/search-result/template.hbs
app/controllers/discover.js
app/templates/index.hbs

Change types --> type for backwards compatibility.
* query param types --> type
None

[Fix] Change query param types --> type

---

app/index.html
config/environment.js
ember-cli-build.js
package.json
yarn.lock

Add Raven client for production builds

---

CHANGELOG.md
app/controllers/discover.js

Clicking the search button runs a search as if the search box were empty.
Use `allQueryParameters` (from ember-parachute) instead of `queryParameters` (from the implementation before ember-parachute).
--
https://openscience.atlassian.net/browse/SHARE-1057

[SHARE-1057] Fix search button

---

config/environment.js
package.json
yarn.lock

Anonymize IPs, because GDPR.
Switch ember-metrics to a cos-fork that allows setting fields, and configure it to add `anonymizeIp: true`
n/a
https://openscience.atlassian.net/browse/SHARE-1084

[SHARE-1084] Set `anonymizeIp` on google analytics requests
