CenterForOpenScience/ember-share

app/controllers/discover.js
app/templates/discover.hbs

Related to #15 
* sort date_updated desc instead of the default
* move sort selector to above divider

Sort date_updated desc and move sort selector

---

app/components/curate-work/component.js
app/components/curate-work/template.hbs

Now that `/api/<type>/<id>/changes` actually works, the curate page gets awfully cluttered. Collapse some things and don't hit the changes and rawdata endpoints until they're expanded.

Collapse Extra, Changes, and Raw Data in curate

---

app/components/link-to-work/component.js
app/components/link-to-work/template.hbs
app/components/page-controls/component.js
app/components/page-controls/template.hbs
app/components/section-related-works/component.js
app/components/section-related-works/template.hbs
app/components/section-work-related-works/template.hbs
app/controllers/agent.js
app/controllers/discover.js
app/controllers/work.js
app/helpers/eq.js
app/helpers/prettify.js
app/mixins/detail.js
app/routes/detail.js
app/templates/agent.hbs
app/templates/discover.hbs
app/utils/mappings.js
tests/unit/helpers/eq-test.js
tests/unit/helpers/prettify-test.js

- Add a `page-controls` component
- Show (paginated) related works on all agents' detail page
- Display relation type for each work -- thoughts on better ways to do this welcome
- Paginate the discover page, and add `page` query param
Organization related works:
Discover page:

[Feature] Paginated related works and search results

---

app/components/search-result/component.js
app/components/search-result/style.css
app/components/search-result/template.hbs
app/controllers/work.js
app/styles/app.scss
app/templates/work.hbs

Put an alert on retracted search results, with a link to their retractions:
Retracted work detail page:
Depends on CenterForOpenScience/SHARE#534

[Feature] Retractions!

---

app/styles/app.scss
app/templates/index.hbs

Display homepage boxes in a row on safari if width allows.
* Don't use flex-wrap on boxes
* see [discussion](https://github.com/backdrop/backdrop-issues/issues/1985) for more details
* Hide search icon on mobile screens
Hiding icon prevents:
* The boxes on the hompage will not wrap on any browser -- the boxes will either be in a row or in a column.
https://openscience.atlassian.net/browse/SHARE-473

[SHARE-473] [Feature] Fix safari spacing bug

---

app/components/search-facet-source/style.css

The donut tooltip likes to wrap way too much. Squash its dreams. Don't let it wrap.
`white-space: nowrap;`
41 bits added per story point.
Very long source names could cause the tooltip to stick off the right side of the window, but only on mobile-size screens which don't have a hover tooltip, anyway.
https://openscience.atlassian.net/browse/SHARE-464

[SHARE-464][Feature] Don't wrap donut tooltips.

---

app/components/query-syntax/component.js
app/components/query-syntax/template.hbs
app/controllers/discover.js
app/helpers/eq.js
app/router.js
app/routes/discover.js
app/styles/app.scss
app/templates/discover.hbs
app/templates/elastic-down.hbs

Display error messages on the discover page when a query fails, instead of leaving the loading indicator up forever.
When Elasticsearch is unreachable (`50x` error), hide the discover page and tell them to try again later:
When Elastic fails to parse the query (`400` error), display a quick overview of query syntax:
Also, wrap the `application-error` page in a bootstrap container, so it'll look less broken.
https://openscience.atlassian.net/browse/SHARE-480

[SHARE-480][Feature] Search error messages

---

app/components/search-result/component.js
app/components/search-result/template.hbs
app/controllers/work.js
app/templates/work.hbs

*** Should be merged after https://github.com/CenterForOpenScience/SHARE/pull/548
Handle html in description so it is more user friendly.
None
https://openscience.atlassian.net/browse/SHARE-470

[SHARE-470] [Feature] Render html on discover and detail page

---

app/components/search-facet-typeahead/component.js
app/components/search-facet-worktype/component.js
app/components/search-result/component.js
app/components/search-result/template.hbs
app/controllers/discover.js
app/controllers/sources.js
app/utils/elastic-query.js

Update elastic queries to use the changed mappings and improved autocomplete setup in CenterForOpenScience/SHARE#543.
In the `search-facet-typeahead` and on the sources page, make a regular elastic query on `name.autocomplete` instead of using the `_suggest` endpoint.
Display only creators in search results, not PIs or generic contributors.
Results will load slightly slower than with the completion suggester, but hopefully the better results are worth the wait. If it's too slow, we could remove `fuzziness: 'AUTO'`.
https://openscience.atlassian.net/browse/SHARE-499

[SHARE-499][SHARE-522][Feature] Better elastic suggestions

---

app/routes/detail.js

When someone goes to something like https://share.osf.io/agent/6424F-604-9B2 it redirects them to https://share.osf.io/person/6424F-604-9B2, but causes ember to call pushState, so hitting the back button retriggers the redirect. This fixes it.

use replaceWith for detail transitions

---

app/components/search-facet-worktype-button/component.js
app/components/search-facet-worktype/style.scss
app/components/search-facet-worktype/template.hbs
app/components/search-result/component.js
app/controllers/discover.js
app/controllers/work.js
app/templates/work.hbs
app/utils/elastic-query.js
config/environment.js

Remove 'Creative Work' from UI to make it more user-friendly.
- Update type on detail view
- Update type in search results
- Remove creative work in type facet and replace with 'Not Categorized'
- Update type filter for creative work
The creative work filter now works differently than all of the other filters: it doesn't display subtypes.
https://openscience.atlassian.net/browse/SHARE-600

[SHARE-600][Improvement] Don't use 'CreativeWork' in UI

---

app/controllers/index.js

Update the placeholder for the search bar on the landing page so the wording is more meaningful.
'search events' --> 'search scholarly works'
None
https://openscience.atlassian.net/browse/SHARE-607

[SHARE-607][Improvement] Update placeholder for search bar on landing page

---

app/components/sortby-dropdown/styles.scss
app/components/sortby-dropdown/template.hbs

Sort icon displayed below dropdown on Firefox.
* Truncate label text in Chrome/Safari if necessary 
* Fix sort icon vertical location in Firefox
Firefox text still overlaps for the longest option. `text-overflow: ellipsis;` is not working for some reason.
https://openscience.atlassian.net/browse/SHARE-602

[SHARE-602][Feature-fix] Fix arrows in Firefox

---

app/controllers/sources.js

*While on this page*
Capitalize the placeholder in the search bar to be more consistent across pages and sites.
None

[SHARE-653][Improvement] Capitalize search bar placeholder

---

app/components/search-result/component.js
app/components/search-result/template.hbs

Don't convert timezone of date published and date updated in search results.
Ensured times stayed in UTC by not using the `moment-format` helper in the search results.
None
https://openscience.atlassian.net/browse/SHARE-573

[SHARE-573][Bug] Don't convert timezone in search results

---

app/components/faceted-search/style.scss
app/components/help-text-tooltip/template.hbs
app/components/navbar-component/style.scss
app/components/navbar-component/template.hbs
app/components/search-facet-daterange/component.js
app/components/search-facet-daterange/style.scss
app/components/search-facet-daterange/template.hbs
app/components/search-facet-worktype-button/style.scss
app/components/search-facet-worktype-button/template.hbs
app/components/search-result/component.js
app/components/search-result/style.scss
app/components/search-result/template.hbs
app/components/sortby-dropdown/template.hbs
app/controllers/discover.js
app/routes/discover.js
app/styles/app.scss
app/templates/discover.hbs

Make the discover page consistent.
Before:
After:
* restrict width to max page width
* left justified with results instead of centered
* add placeholder in search bar
* remove all results and aggregated sources from under search bar
* pagination is only on the bottom
* move 'Clear filters' to side bar
* move side bar to right
* All time --> All dates in date filter
* 'Clear filters' --> 'Reset all filters' in side bar
* tool-tips go up instead of to the right since the side bar moved
* selected type looks more similar to the other filters
* title is at the very top of each result
* show only year for date published
* remove "filter links" from search results so only things that have detail pages are clickable
* when the description is truncated it won't cut words in half
* remove space …

[SHARE-634][Improvement] Make the discover page consistent

---

app/components/cos-footer/template.hbs
app/components/registration-status/component.js
app/router.js
app/templates/notfound.hbs
app/templates/registration/form.hbs

Expose the share support email in footer and change `support@osf.io` to `share-support@osf.io`.
* API --> Contact in footer since the API can be reached through the developer docs
* `support@osf.io` --> `share-support@osf.io`
* removed unused `support` route
None
https://openscience.atlassian.net/browse/SHARE-606

[SHARE-606][Improvement] Expose share support email in footer

---

app/controllers/discover.js
app/controllers/sources.js
app/routes/sources.js
config/environment.js

The number of sources on the sources page differ from the number on the discover page.
Filter API results based on an elastic aggregation.
Only sources with data will display on the sources page. On staging and locally there might be only a few sources listed.
https://openscience.atlassian.net/browse/SHARE-938

[SHARE-938][Improvement] Only display sources with data on sources page

---

CHANGELOG.md
app/components/cos-footer/component.js
app/components/cos-footer/template.hbs

The copyright in the footer says 2017 when it should say 2018.
**Before:**
**After:**
None
https://openscience.atlassian.net/browse/SHARE-1030

[SHARE-1030][Improvement] Use current year for copyright in footer

---

app/components/section-links/template.hbs

DOI's and other links are currently hidden in the record level view for external links.Changing the external link uri to display full uri instead of just host
Changed link label from identifier.host to identifier.uri
Related ticket needs to be created re:conversation with Lauren B
https://openscience.atlassian.net/browse/SHARE-1083

[SHARE-1083] Changing the external link uri to display full uri instead of just host

---

app/adapters/application.js
app/components/navbar-component/template.hbs
app/components/uri-display/component.js
app/components/uri-display/template.hbs
app/controllers/sources.js
app/controllers/suid.js
app/models/formatted-metadata-record.js
app/models/source-config.js
app/models/source.js
app/models/suid.js
app/router.js
app/routes/detail.js
app/routes/sources.js
app/serializers/application.js
app/templates/suid.hbs
app/utils/mappings.js
ember-cli-build.js
package.json
yarn.lock

gentle-touch changes to avoid blocking backend work -- in anticipation of deleting `ShareObject`, search results now have ids that correspond with their `SourceUniqueIdentifier` ("suid") instead of an `AbstractCreativeWork`
- add models to get some useful info from the api:
- `suid`
- `source`
- `source-config`
- `formatted-metadata-record`
- add a `suid` route to display info from a suid id
- new dependencies:
- `xml-formatter` -- for rendering oai_dc metadata cards
- `ember-cli-cjs-transform` -- for importing `xml-formatter`
hoping to circle back before long and give this app some needed attention

[ENG-2650] prepare for the future -- handle suid ids
